/**
 * 
 */
var profileData = {  
		   "result_code":1,
		   "result_data":{  
		      "name":"홍길동",
		      "cellphone":"821012345678",
		      "face":"../../design/html_noinc/images/post/thumb.jpg",
		      "thumbnail":"../../design/html_noinc/images/post/thumb.jpg",
		      "birthday":"0628",
		      "email":"",
		      "country":"KR",
		      "birthdate":"????0628+",
		      "naver_id":"aaaa",
		      "id":"m2_2k3p58kazyiovdxsvvkoyyfpzqhxekoai4qgdh4",
		      "user_no":17799208,
		      "need_cellphone_change":false,
		      "need_cellphone_authorize":false,
		      "is_lunar":false,
		      "facebook_user_id":"",
		      "line_user_id":"",
		      "is_exist_password":false,
		      "is_open_me2day":false,
		      "contract_language":"ko_KR",
		      "pc_web_language":"ko",
		      "country_code":82,
		      "is_email_verified":false,
		      "personal_info_agreements":{  
		         "birthday":true,
		         "phone_number":true,
		         "email":false,
		         "location":false,
		         "profile_image":true,
		         "gender":false,
		         "contacts":false
		      }
		   }
		};
var groupListData = {  
		   "result_code":1,
		   "result_data":{  
		      "bands":[  
		         {  
		            "cover":"http://band.phinf.campmobile.net/20130402_109/m2_2k3p58kcnf0kez8zxi2m2jzmd8g86c1ki2sxyr8_1364893983275cXPXA_JPEG/m2_2k3p58kcnf0kez8zxi2m2jzmd8g86c1ki2sxyr8_8623495079777822448.jpg",
		            "name":"dbs1",
		            "since":"20130402",
		            "member_count":13,
		            "properties":{  
		               "permitted_operation":[  
		                  "name_cover_edit",
		                  "notice_edit",
		                  "posting",
		                  "schedule",
		                  "invitation",
		                  "media_download",
		                  "commenting"
		               ],
		               "is_member_list_enabled":true,
		               "is_mention_enabled":true,
		               "is_member_selectable_for_chat":true,
		               "is_member_selectable_for_present":true,
		               "is_member_selectable_for_invitation":true,
		               "is_band_chat_enabled":true,
		               "is_bill_split_enabled":true,
		               "is_named_vote_enabled":true
		            },
		            "access_status":{  
		               "updated":false,
		               "chat":{  
		                  "updated":false,
		                  "updated_at":"1970-01-01T09:00:00+0900",
		                  "accessed_at":"1970-01-02T09:00:00+0900"
		               }
		            },
		            "band_id":"m2_hf12gcuk",
		            "theme_color":"BAND_5",
		            "band_no":3562154,
		            "room_id":"M5-5rsuj"
		         },
		         {  
		            "cover":"http://coresos.phinf.naver.net/a_2fe5j1_g/ij6Ud0151pgi9yu24l82z_mj7dom.jpg",
		            "name":"dbs2",
		            "since":"20121009",
		            "member_count":12,
		            "properties":{  
		               "permitted_operation":[  
		                  "name_cover_edit",
		                  "notice_edit",
		                  "posting",
		                  "schedule",
		                  "invitation",
		                  "media_download",
		                  "commenting"
		               ],
		               "is_member_list_enabled":true,
		               "is_mention_enabled":true,
		               "is_member_selectable_for_chat":true,
		               "is_member_selectable_for_present":true,
		               "is_member_selectable_for_invitation":true,
		               "is_band_chat_enabled":true,
		               "is_bill_split_enabled":true,
		               "is_named_vote_enabled":true
		            },
		            "access_status":{  
		               "updated":false,
		               "chat":{  
		                  "updated":false,
		                  "updated_at":"1970-01-01T09:00:00+0900",
		                  "accessed_at":"1970-01-02T09:00:00+0900"
		               }
		            },
		            "band_id":"m2_h82wd4x7",
		            "theme_color":"BAND_7",
		            "band_no":699871,
		            "room_id":"M_-yt9vl"
		         },
		         {  
		            "cover":"http://coresos.phinf.naver.net/a_2fdfb1_g/58hUd01516cv6b37ixnhz_lbeccp.jpg",
		            "name":"dbs3",
		            "since":"20140818",
		            "member_count":3,
		            "properties":{  
		               "permitted_operation":[  
		                  "name_cover_edit",
		                  "notice_edit",
		                  "posting",
		                  "schedule",
		                  "invitation",
		                  "media_download",
		                  "commenting"
		               ],
		               "is_member_list_enabled":true,
		               "is_mention_enabled":true,
		               "is_member_selectable_for_chat":true,
		               "is_member_selectable_for_present":true,
		               "is_member_selectable_for_invitation":true,
		               "is_band_chat_enabled":true,
		               "is_bill_split_enabled":true,
		               "is_named_vote_enabled":true
		            },
		            "access_status":{  
		               "updated":false,
		               "chat":{  
		                  "updated":false,
		                  "updated_at":"1970-01-01T09:00:00+0900",
		                  "accessed_at":"1970-01-02T09:00:00+0900"
		               }
		            },
		            "band_id":"50016057",
		            "theme_color":"BAND_13",
		            "band_no":50016057,
		            "room_id":"C3ogWV"
		         }
		      ]
		   }
		};
var messageData = {  
		   "result_code":1,
		   "result_data":{  
		      "channel":{  
		         "notification":"on",
		         "name":"Testing",
		         "type":"public",
		         "status":"ready",
		         "buid":"C3ogWV",
		         "latest_message":"어렵군",
		         "user_status":"ready",
		         "new_message_count":0,
		         "updated_at":1430308292000,
		         "band_cover":"http://coresos.phinf.naver.net/a_2fdfb1_g/58hUd01516cv6b37ixnhz_lbeccp.jpg",
		         "user_count":3,
		         "message_period":"year",
		         "band_name":"dbs3",
		         "latest_message_no":22,
		         "user_last_message_no":22,
		         "latest_message_type":1,
		         "band_no":50016057,
		         "theme_color":"BAND_13",
		         "created_at":1408370165000,
		         "is_default_channel":true
		      },
		      "users":[  
		         {  
		            "status":"ready",
		            "description":"",
		            "name":"친구1",
		            "id":"friend1",
		            "user_no":11667091,
		            "updated_at":1408429391000
		         },
		         {  
		            "status":"ready",
		            "description":"ㅡㅡ",
		            "name":"나",
		            "id":"my",
		            "face":"http://band.phinf.campmobile.net/20130405_38/m2_2k3p58kazyiovdxsvvkoyyfpzqhxekoai4qgdh4_13651494868383KbVI_JPEG/m2_2k3p58kazyiovdxsvvkoyyfpzqhxekoai4qgdh4_4224433721797927070.jpg",
		            "user_no":17799208,
		            "updated_at":1364861095000
		         },
		         {  
		            "status":"ready",
		            "name":"친구2",
		            "id":"friend2",
		            "face":"http://s.cmstatic.net/pcweb/res/149992/images/template/profile_60x60.gif?type=s75",
		            "user_no":38168623,
		            "updated_at":1408428809000
		         }
		      ],
		      "messages":[  
		         {  
		            "id":19,
		            "type":1,
		            "body":"아아아",
		            "extras":null,
		            "tid":757136028,
		            "member_count":3,
		            "created_at":1429862654000,
		            "read_count":2,
		            "writer_id":"my",
		            "writer_no":17799208
		         },
		         {  
		            "id":20,
		            "type":1,
		            "body":"테스트",
		            "extras":null,
		            "tid":417571494,
		            "member_count":3,
		            "created_at":1430306937000,
		            "read_count":2,
		            "writer_id":"friend1",
		            "writer_no":17799208
		         },
		         {  
		            "id":21,
		            "type":1,
		            "body":"테스트2",
		            "extras":null,
		            "tid":1898625261,
		            "member_count":3,
		            "created_at":1430307123000,
		            "read_count":2,
		            "writer_id":"friend2",
		            "writer_no":17799208
		         },
		         {  
		            "id":22,
		            "type":1,
		            "body":"어렵군",
		            "extras":null,
		            "tid":971203853,
		            "member_count":3,
		            "created_at":1430308292000,
		            "read_count":2,
		            "writer_id":"my",
		            "writer_no":17799208
		         }
		      ],
		      "last_message_no":22,
		      "first_message_no":19,
		      "new_message_count":0,
		      "is_full_sync":true,
		      "server_time":1430386702000
		   }
		}